import { Router } from "express";

import userRoutes from "./userRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import buildCaptureExtensionRoutes from "./buildCaptureExtensionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import chatRoutes from "./chatRoutes";
import invoiceRoutes from "./invoicesRoutes";
import subscriptionRoutes from "./subScriptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import pwaRoutes from "./pwaRoutes";
import versionRoutes from "./versionRoutes";
import ticketzOSSRoutes from "./ticketzOSSRoutes";
import i18nRoutes from "./i18nRoutes";
import wavoipRoutes from "./wavoipRoutes";
import aiRoutes from "./aiRoutes";

const heavyRoutes = Router();

heavyRoutes.use(userRoutes);
heavyRoutes.use(contactRoutes);
heavyRoutes.use(ticketRoutes);
heavyRoutes.use(buildCaptureExtensionRoutes);
heavyRoutes.use(whatsappRoutes);
heavyRoutes.use(messageRoutes);
heavyRoutes.use(whatsappSessionRoutes);
heavyRoutes.use(queueRoutes);
heavyRoutes.use(companyRoutes);
heavyRoutes.use(planRoutes);
heavyRoutes.use(ticketNoteRoutes);
heavyRoutes.use(quickMessageRoutes);
heavyRoutes.use(helpRoutes);
heavyRoutes.use(dashboardRoutes);
heavyRoutes.use(queueOptionRoutes);
heavyRoutes.use(scheduleRoutes);
heavyRoutes.use(tagRoutes);
heavyRoutes.use(contactListRoutes);
heavyRoutes.use(contactListItemRoutes);
heavyRoutes.use(campaignRoutes);
heavyRoutes.use(campaignSettingRoutes);
heavyRoutes.use(announcementRoutes);
heavyRoutes.use(chatRoutes);
heavyRoutes.use(subscriptionRoutes);
heavyRoutes.use(invoiceRoutes);
heavyRoutes.use(ticketTagRoutes);
heavyRoutes.use(pwaRoutes);
heavyRoutes.use(versionRoutes);
heavyRoutes.use(ticketzOSSRoutes);
heavyRoutes.use(i18nRoutes);
heavyRoutes.use(wavoipRoutes);
heavyRoutes.use(aiRoutes);

export default heavyRoutes;
